=== KiriBogach/arsoProject/Bogach-Kyryl-entrega1/xml/ciudad.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT ciudad (nombre, codigo, pais, poblacion, ubicacion, bdpedia?, wikipedia?, fechaActualizacion, infoMeteorologica?, sitiosInteres)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT poblacion (#PCDATA)>
<!ELEMENT ubicacion (latitud, longitud)>
<!ELEMENT latitud (#PCDATA)>
<!ELEMENT longitud (#PCDATA)>
<!ELEMENT bdpedia (#PCDATA)>
<!ELEMENT wikipedia (#PCDATA)>
<!ELEMENT fechaActualizacion (#PCDATA)>
<!ELEMENT infoMeteorologica (tiempoObservacion, nombreEstacion, temperatura, nubes)>
<!ELEMENT tiempoObservacion (#PCDATA)>
<!ELEMENT nombreEstacion (#PCDATA)>
<!ELEMENT temperatura (#PCDATA)>
<!ELEMENT nubes (#PCDATA)>
<!ELEMENT sitiosInteres (sitio*)>
<!ELEMENT sitio (nombre, codigo)>

=== KiriBogach/arsoProject/Bogach-Kyryl-entrega1/xml-bd/cartagenaDTD.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE ciudad SYSTEM "../xml/ciudad.dtd">

<ciudad>
	<nombre>Cartagena</nombre>
	<codigo>2520058</codigo> <!-- restriccion de longitud? numerico? -->
	<pais>Spaiña</pais> <!-- enumerado? yo creo que no -->
	<poblacion>211996</poblacion> <!-- numerico, restriccion de longitud? -->
	<ubicacion> <!-- complex type, seguro -->
		<latitud>37.60512</latitud> <!-- double, restriccion de longitud? -->
		<longitud>-0.98623</longitud> <!-- '''' -->
	</ubicacion>
	<bdpedia>url,no tengo ganas de copiar</bdpedia> <!-- regex para url??? no creo no? -->
	<wikipedia>otraurl</wikipedia>
	<fechaActualizacion>2012-03-04</fechaActualizacion> <!-- fecha, el único campo claro -->
	<infoMeteorologica> <!-- tipo complejo, hacer externo -->
		<tiempoObservacion>2019-02-04T09:00:00</tiempoObservacion> <!-- no hay un formato para la fecha, al menos tal y como está ¿crearlo? -->
		<nombreEstacion>la estacion española</nombreEstacion>
		<temperatura>14</temperatura> <!-- int o double? -->
		<nubes>clouds and visibility ok</nubes> <!-- enumerado? está raro -->
	</infoMeteorologica>
	<sitiosInteres> <!-- otro tipo complejo -->
		<sitio>
			<nombre>castillo los patos</nombre>
			<codigo>123123123</codigo> <!-- mismo formato que el codigo de antes? -->
		</sitio>
	</sitiosInteres>
</ciudad>

=== KiriBogach/arsoProject/xml-bd/orihuelaDTD.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE ciudad SYSTEM "../xml/ciudad.dtd">

<ciudad>
	<nombre>Orihuela</nombre>
	<codigo>2513076</codigo>
	<pais>España</pais>
	<poblacion>154023</poblacion>
	<ubicacion>
		<latitud>14</latitud>
		<longitud>18</longitud>
	</ubicacion>
	<bdpedia>Opcional - Uso de regex? http://es.dbpedia.org</bdpedia>
	<wikipedia>Opcional - Uso de regex?
		https://es.wikipedia.org/wiki/Orihuela
	</wikipedia>
	<fechaActualizacion>2005-02-02</fechaActualizacion>
	<infoMeteorologica>
		<tiempoObservacion>2004-02-02T09:00:00</tiempoObservacion>
		<nombreEstacion>Estación Miguel Hernández</nombreEstacion>
		<temperatura>23.2</temperatura>
		<nubes>No</nubes>
	</infoMeteorologica>
	<sitiosInteres>
		<sitio>
			<nombre>La Glorieta</nombre>
			<codigo>2513080</codigo>
		</sitio>
	</sitiosInteres>
</ciudad>

=== KiriBogach/arsoProject/xml-bd/ciudadGeneratedDTD.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE ciudad SYSTEM "../xml/ciudad.dtd" >

<ciudad>
	<nombre>nombre</nombre>
	<codigo>codigo</codigo>
	<pais>pais</pais>
	<poblacion>poblacion</poblacion>
	<ubicacion>
		<latitud>latitud</latitud>
		<longitud>longitud</longitud>
	</ubicacion>
	<bdpedia>bdpedia</bdpedia>
	<wikipedia>wikipedia</wikipedia>
	<fechaActualizacion>fechaActualizacion</fechaActualizacion>
	<infoMeteorologica>
		<tiempoObservacion>tiempoObservacion</tiempoObservacion>
		<nombreEstacion>nombreEstacion</nombreEstacion>
		<temperatura>temperatura</temperatura>
		<nubes>nubes</nubes>
	</infoMeteorologica>
	<sitiosInteres>
		<sitio>
			<nombre>nombre</nombre>
			<codigo>codigo</codigo>
		</sitio>
	</sitiosInteres>
</ciudad>
