=== KiriBogach/arsoProject/Bogach-Kyryl-entrega1/xml/ciudad.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/ciudad"
	xmlns:tns="http://www.example.org/ciudad"
	elementFormDefault="qualified">

	<!-- Elemento raÃ­z: -->

	<xs:element name="ciudad">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="tns:tipoIdentificador">
					<xs:sequence>
						<xs:element name="pais" type="xs:string" />
						<xs:element name="poblacion" type="xs:integer" />
						<xs:element name="ubicacion" type="tns:tipoUbicacion" />
						<xs:element name="bdpedia" type="xs:anyURI"
							minOccurs="0" />
						<xs:element name="wikipedia" type="xs:anyURI"
							minOccurs="0" />
						<xs:element name="fechaActualizacion" type="xs:date" />
						<xs:element name="infoMeteorologica"
							type="tns:tipoInformacionMeteorologica" minOccurs="0" />
						<xs:element name="sitiosInteres"
							type="tns:tipoSitiosInteres" />
						<xs:element name="libros" type="tns:tipoLibros" />
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<!-- Tipos: -->

	<xs:complexType name="tipoIdentificador">
		<xs:sequence>
			<xs:element name="nombre" type="xs:string" />
			<xs:element name="codigo" type="xs:unsignedLong" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="tipoInformacionMeteorologica">
		<xs:sequence>
			<xs:element name="tiempoObservacion" type="xs:dateTime" />
			<xs:element name="nombreEstacion" type="xs:string" />
			<xs:element name="temperatura" type="xs:decimal" />
			<xs:element name="nubes" type="xs:string" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="tipoUbicacion">
		<xs:sequence>
			<xs:element name="latitud" type="xs:decimal" />
			<xs:element name="longitud" type="xs:decimal" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="tipoSitiosInteres">
		<xs:sequence>
			<xs:element name="sitio" type="tns:tipoIdentificador"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="tipoLibros">
		<xs:sequence>
			<xs:element name="libro" type="tns:tipoLibro" minOccurs="0" maxOccurs="3"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="tipoLibro">
		<xs:sequence>
			<xs:element name="titulo" type="xs:string" />
			<xs:element name="identificador" type="xs:string" />
			<xs:element name="ISBN" type="xs:string" minOccurs="0"/>
			<xs:element name="urlImagen" type="xs:anyURI" />
			<xs:element name="urlGoogleBooks" type="xs:anyURI" />
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== KiriBogach/arsoProject/xml-bd/3117735.xml
<?xml version="1.0" ?><ciudad xmlns="http://www.example.org/ciudad" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/ciudad ../xml/ciudad.xsd"><nombre>Madrid</nombre><codigo>3117735</codigo><pais>ES</pais><poblacion>3255944</poblacion><ubicacion><latitud>40.4165</latitud><longitud>-3.70256</longitud></ubicacion><bdpedia>http://dbpedia.org/resource/Madrid</bdpedia><wikipedia>https://en.wikipedia.org/wiki/Madrid</wikipedia><fechaActualizacion>2018-07-30</fechaActualizacion><infoMeteorologica><tiempoObservacion>2019-02-24T05:00:00</tiempoObservacion><nombreEstacion>Madrid / Cuatro Vientos</nombreEstacion><temperatura>19.0</temperatura><nubes>clouds and visibility OK</nubes></infoMeteorologica><sitiosInteres><sitio><nombre>Hostal Alhambra Suites</nombre><codigo>9882263</codigo></sitio><sitio><nombre>Puerta del Sol</nombre><codigo>6946861</codigo></sitio><sitio><nombre>Sol</nombre><codigo>6545083</codigo></sitio><sitio><nombre>Gay Hostal Puerta del Sol</nombre><codigo>6501834</codigo></sitio><sitio><nombre>Hostal Ana Belen</nombre><codigo>10241280</codigo></sitio><sitio><nombre>SUSTITUIR Puerta del Sol</nombre><codigo>6947430</codigo></sitio><sitio><nombre>Hostal Pretoria</nombre><codigo>10240946</codigo></sitio><sitio><nombre>Hostal Suite Alhambra</nombre><codigo>10240963</codigo></sitio><sitio><nombre>Paris</nombre><codigo>6476845</codigo></sitio></sitiosInteres></ciudad>

=== KiriBogach/arsoProject/xml-bd/ciudadGeneratedSchema.xml
<?xml version="1.0" encoding="UTF-8"?>

<ciudad xmlns="http://www.example.org/ciudad"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/ciudad ../xml/ciudad.xsd ">

	<nombre>nombre</nombre>
	<codigo>0</codigo>
	<pais>pais</pais>
	<poblacion>1</poblacion>
	<ubicacion>
		<latitud>0.0</latitud>
		<longitud>0.0</longitud>
	</ubicacion>
	<bdpedia>http://tempuri.org</bdpedia>
	<wikipedia>http://tempuri.org</wikipedia>
	<fechaActualizacion>2001-01-01</fechaActualizacion>
	<infoMeteorologica>
		<tiempoObservacion>2001-12-31T12:00:00</tiempoObservacion>
		<nombreEstacion>nombreEstacion</nombreEstacion>
		<temperatura>0.0</temperatura>
		<nubes>nubes</nubes>
	</infoMeteorologica>
	<sitiosInteres>
		<sitio>
			<nombre>nombre</nombre>
			<codigo>0</codigo>
		</sitio>
	</sitiosInteres>
</ciudad>

=== KiriBogach/arsoProject/xml-bd/2513718.xml
<?xml version="1.0" ?>
<ciudad xmlns="http://www.example.org/ciudad"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/ciudad ../xml/ciudad.xsd">
	<nombre>Molï¿½ns</nombre>
	<codigo>2513718</codigo>
	<pais>ES</pais>
	<poblacion>0</poblacion>
	<ubicacion>
		<latitud>38.08194</latitud>
		<longitud>-0.90865</longitud>
	</ubicacion>
	<fechaActualizacion>2018-06-08</fechaActualizacion>
	<infoMeteorologica>
		<tiempoObservacion>2019-02-24T05:30:00</tiempoObservacion>
		<nombreEstacion>Murcia / San Javier</nombreEstacion>
		<temperatura>15.0</temperatura>
		<nubes>scattered clouds</nubes>
	</infoMeteorologica>
	<sitiosInteres>
		<sitio>
			<nombre>Hurchillo</nombre>
			<codigo>2516486</codigo>
		</sitio>
		<sitio>
			<nombre>Teatro Circo</nombre>
			<codigo>8436610</codigo>
		</sitio>
		<sitio>
			<nombre>La Campaneta</nombre>
			<codigo>2516117</codigo>
		</sitio>
		<sitio>
			<nombre>Aparthotel Palmera Beach</nombre>
			<codigo>11000851</codigo>
		</sitio>
		<sitio>
			<nombre>Edificio Carmen Conde</nombre>
			<codigo>8349591</codigo>
		</sitio>
		<sitio>
			<nombre>Palacio de Tudemir</nombre>
			<codigo>6482280</codigo>
		</sitio>
		<sitio>
			<nombre>Bigastro</nombre>
			<codigo>6355420</codigo>
		</sitio>
		<sitio>
			<nombre>Jessica Beach</nombre>
			<codigo>7288210</codigo>
		</sitio>
		<sitio>
			<nombre>Bigastro</nombre>
			<codigo>2520955</codigo>
		</sitio>
	</sitiosInteres>
</ciudad>

=== KiriBogach/arsoProject/xml-bd/orihuelaSchema.xml
<?xml version="1.0" encoding="UTF-8"?>

<ciudad xmlns="http://www.example.org/ciudad"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/ciudad ../xml/ciudad.xsd ">
	<nombre>Orihuela</nombre>
	<codigo>2513076</codigo>
	<pais>España</pais>
	<poblacion>154023</poblacion>
	<ubicacion>
		<latitud>14</latitud>
		<longitud>18</longitud>
	</ubicacion>
	<bdpedia>Opcional - Uso de regex? http://es.dbpedia.org</bdpedia>
	<wikipedia>Opcional - Uso de regex?
		https://es.wikipedia.org/wiki/Orihuela
	</wikipedia>
	<fechaActualizacion>2005-02-02</fechaActualizacion>
	<infoMeteorologica>
		<tiempoObservacion>2004-02-02T09:00:00</tiempoObservacion>
		<nombreEstacion>Estación Miguel Hernández</nombreEstacion>
		<temperatura>23.2</temperatura>
		<nubes>No</nubes>
	</infoMeteorologica>
	<sitiosInteres>
		<sitio>
			<nombre>La Glorieta</nombre>
			<codigo>2513080</codigo>
		</sitio>
	</sitiosInteres>
</ciudad>
