=== KiriBogach/arsoProject/Bogach-Kyryl-entrega1/xml/ciudad.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/ciudad"
	xmlns:tns="http://www.example.org/ciudad"
	elementFormDefault="qualified">

	<!-- Elemento raÃ­z: -->

	<xs:element name="ciudad">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="tns:tipoIdentificador">
					<xs:sequence>
						<xs:element name="pais" type="xs:string" />
						<xs:element name="poblacion" type="xs:integer" />
						<xs:element name="ubicacion" type="tns:tipoUbicacion" />
						<xs:element name="bdpedia" type="xs:anyURI"
							minOccurs="0" />
						<xs:element name="wikipedia" type="xs:anyURI"
							minOccurs="0" />
						<xs:element name="fechaActualizacion" type="xs:date" />
						<xs:element name="infoMeteorologica"
							type="tns:tipoInformacionMeteorologica" minOccurs="0" />
						<xs:element name="sitiosInteres"
							type="tns:tipoSitiosInteres" />
						<xs:element name="libros" type="tns:tipoLibros" />
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<!-- Tipos: -->

	<xs:complexType name="tipoIdentificador">
		<xs:sequence>
			<xs:element name="nombre" type="xs:string" />
			<xs:element name="codigo" type="xs:unsignedLong" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="tipoInformacionMeteorologica">
		<xs:sequence>
			<xs:element name="tiempoObservacion" type="xs:dateTime" />
			<xs:element name="nombreEstacion" type="xs:string" />
			<xs:element name="temperatura" type="xs:decimal" />
			<xs:element name="nubes" type="xs:string" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="tipoUbicacion">
		<xs:sequence>
			<xs:element name="latitud" type="xs:decimal" />
			<xs:element name="longitud" type="xs:decimal" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="tipoSitiosInteres">
		<xs:sequence>
			<xs:element name="sitio" type="tns:tipoIdentificador"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="tipoLibros">
		<xs:sequence>
			<xs:element name="libro" type="tns:tipoLibro" minOccurs="0" maxOccurs="3"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="tipoLibro">
		<xs:sequence>
			<xs:element name="titulo" type="xs:string" />
			<xs:element name="identificador" type="xs:string" />
			<xs:element name="ISBN" type="xs:string" minOccurs="0"/>
			<xs:element name="urlImagen" type="xs:anyURI" />
			<xs:element name="urlGoogleBooks" type="xs:anyURI" />
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== KiriBogach/arsoProject/Bogach-Kyryl-entrega1/xml-bd/3687238.xml
<?xml version="1.0" ?><ciudad xmlns="http://www.example.org/ciudad" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/ciudad ../xml/ciudad.xsd"><nombre>Cartagena</nombre><codigo>3687238</codigo><codigoPais>CO</codigoPais><nombrePais></nombrePais><poblacion>952024</poblacion><ubicacion><latitud>10.39972</latitud><longitud>-75.51444</longitud></ubicacion><bdpedia>http://dbpedia.org/resource/Cartagena%2C_Colombia</bdpedia><wikipedia>https://en.wikipedia.org/wiki/Cartagena%2C_Colombia</wikipedia><fechaActualizacion>2018-04-20</fechaActualizacion><infoMeteorologica><tiempoObservacion>2019-04-06T04:00:00</tiempoObservacion><nombreEstacion>Cartagena / Rafael Nunez</nombreEstacion><temperatura>33.0</temperatura><nubes>few clouds</nubes></infoMeteorologica><sitiosInteres><sitio><nombre>Amberes</nombre><codigo>3689976</codigo></sitio><sitio><nombre>Bruselas</nombre><codigo>3688474</codigo></sitio><sitio><nombre>Lomas de Mari√≥n</nombre><codigo>3675258</codigo></sitio><sitio><nombre>Armenia</nombre><codigo>3689554</codigo></sitio><sitio><nombre>Movich Hotel Cartagena De Indias Slh</nombre><codigo>9612088</codigo></sitio><sitio><nombre>Acueducto Cartagena</nombre><codigo>3687237</codigo></sitio><sitio><nombre>Barrio El Prado</nombre><codigo>3689126</codigo></sitio><sitio><nombre>Cartagena Water Treatment Plant</nombre><codigo>9222770</codigo></sitio><sitio><nombre>Hotel Avenida Buenos Aires</nombre><codigo>10233251</codigo></sitio></sitiosInteres></ciudad>

=== KiriBogach/arsoProject/Bogach-Kyryl-entrega1/xml-bd/4570319.xml
<?xml version="1.0" ?><ciudad xmlns="http://www.example.org/ciudad" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/ciudad ../xml/ciudad.xsd"><nombre>Beauty Spot School</nombre><codigo>4570319</codigo><pais>US</pais><poblacion>0</poblacion><ubicacion><latitud>34.06822</latitud><longitud>-79.35922</longitud></ubicacion><fechaActualizacion>2010-09-05</fechaActualizacion><infoMeteorologica><tiempoObservacion>2019-03-23T03:35:00</tiempoObservacion><nombreEstacion>MARION</nombreEstacion><temperatura>14.0</temperatura><nubes>n/a</nubes></infoMeteorologica><sitiosInteres><sitio><nombre>Bay Cemetery</nombre><codigo>4570181</codigo></sitio><sitio><nombre>Leggett Millpond Dam D-0511</nombre><codigo>4584903</codigo></sitio><sitio><nombre>Centenary Church</nombre><codigo>4574102</codigo></sitio><sitio><nombre>Leggett Mill Pond</nombre><codigo>4584902</codigo></sitio><sitio><nombre>Marion</nombre><codigo>4586272</codigo></sitio><sitio><nombre>Smith Mill Pond</nombre><codigo>4596051</codigo></sitio><sitio><nombre>Saint Marys Church</nombre><codigo>4594223</codigo></sitio><sitio><nombre>Little Reedy Creek</nombre><codigo>4585418</codigo></sitio><sitio><nombre>Terrell Bay</nombre><codigo>4598409</codigo></sitio></sitiosInteres></ciudad>

=== KiriBogach/arsoProject/xml-bd/4570320.xml
<?xml version="1.0" ?><ciudad xmlns="http://www.example.org/ciudad" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/ciudad ../xml/ciudad.xsd"><nombre>Beaver Branch</nombre><codigo>4570320</codigo><pais>US</pais><poblacion>0</poblacion><ubicacion><latitud>33.65541</latitud><longitud>-81.79955</longitud></ubicacion><fechaActualizacion></fechaActualizacion><infoMeteorologica><tiempoObservacion>2019-03-23T03:35:00</tiempoObservacion><nombreEstacion>AIKEN</nombreEstacion><temperatura>14.0</temperatura><nubes>n/a</nubes></infoMeteorologica><sitiosInteres><sitio><nombre>Green Cemetery</nombre><codigo>4580405</codigo></sitio><sitio><nombre>Kines Fork</nombre><codigo>4584052</codigo></sitio><sitio><nombre>Little Horse Creek</nombre><codigo>4585348</codigo></sitio><sitio><nombre>Sunny Brook</nombre><codigo>4597991</codigo></sitio><sitio><nombre>Bear Branch</nombre><codigo>4570230</codigo></sitio><sitio><nombre>Gopher Branch</nombre><codigo>4580110</codigo></sitio><sitio><nombre>Long Branch</nombre><codigo>4585646</codigo></sitio><sitio><nombre>Smiths Lake Dam D-2024</nombre><codigo>4596093</codigo></sitio><sitio><nombre>Smiths Lake</nombre><codigo>4596091</codigo></sitio></sitiosInteres></ciudad>

=== KiriBogach/arsoProject/xml-bd/2225705.xml
<?xml version="1.0" ?><ciudad xmlns="http://www.example.org/ciudad" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/ciudad ../xml/ciudad.xsd"><nombre>Mvané</nombre><codigo>2225705</codigo><pais>CM</pais><poblacion>0</poblacion><ubicacion><latitud>4.51667</latitud><longitud>12.13333</longitud></ubicacion><fechaActualizacion>2011-03-06</fechaActualizacion><infoMeteorologica><tiempoObservacion>2019-03-13T09:00:00</tiempoObservacion><nombreEstacion>Yaounde</nombreEstacion><temperatura>27.0</temperatura><nubes>broken clouds</nubes></infoMeteorologica><sitiosInteres><sitio><nombre>Ndakouda</nombre><codigo>2225379</codigo></sitio><sitio><nombre>Mendjuo</nombre><codigo>2227155</codigo></sitio><sitio><nombre>Bipogué</nombre><codigo>2234000</codigo></sitio><sitio><nombre>Mendibi</nombre><codigo>2227173</codigo></sitio><sitio><nombre>Mengondé</nombre><codigo>2227097</codigo></sitio><sitio><nombre>Moum</nombre><codigo>2225883</codigo></sitio><sitio><nombre>Endoum</nombre><codigo>2231945</codigo></sitio><sitio><nombre>Mellé</nombre><codigo>2227247</codigo></sitio><sitio><nombre>Nkoumoutou</nombre><codigo>2223694</codigo></sitio></sitiosInteres></ciudad>

=== KiriBogach/arsoProject/Bogach-Kyryl-entrega1/xml-bd/2520058.xml
<?xml version="1.0" ?><ciudad xmlns="http://www.example.org/ciudad" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/ciudad ../xml/ciudad.xsd"><nombre>Cartagena</nombre><codigo>2520058</codigo><pais>Spain</pais><poblacion>211996</poblacion><ubicacion><latitud>37.60512</latitud><longitud>-0.98623</longitud></ubicacion><bdpedia>http://dbpedia.org/resource/Cartagena%2C_Spain</bdpedia><wikipedia>https://en.wikipedia.org/wiki/Cartagena%2C_Spain</wikipedia><fechaActualizacion>2012-03-04</fechaActualizacion><infoMeteorologica><tiempoObservacion>2019-04-10T02:30:00</tiempoObservacion><nombreEstacion>International airport of the Region of Murcia</nombreEstacion><temperatura>18.0</temperatura><nubes>clouds and visibility OK</nubes></infoMeteorologica><sitiosInteres></sitiosInteres></ciudad>

=== KiriBogach/arsoProject/Bogach-Kyryl-entrega1/xml-bd/2225704.xml
<?xml version="1.0" ?><ciudad xmlns="http://www.example.org/ciudad" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/ciudad ../xml/ciudad.xsd"><nombre>Mvangane</nombre><codigo>2225704</codigo><pais>CM</pais><poblacion>0</poblacion><ubicacion><latitud>2.65602</latitud><longitud>11.74026</longitud></ubicacion><wikipedia>http://dbpedia.org/resource/Mvangane</wikipedia><fechaActualizacion>2011-03-21</fechaActualizacion><infoMeteorologica><tiempoObservacion>2019-03-13T09:00:00</tiempoObservacion><nombreEstacion>Bitam</nombreEstacion><temperatura>26.0</temperatura><nubes>scattered clouds</nubes></infoMeteorologica><sitiosInteres><sitio><nombre>Yem</nombre><codigo>2220912</codigo></sitio><sitio><nombre>Néléjoup</nombre><codigo>2224944</codigo></sitio><sitio><nombre>Bikong</nombre><codigo>2234150</codigo></sitio><sitio><nombre>Kong</nombre><codigo>2230068</codigo></sitio><sitio><nombre>Nko</nombre><codigo>2224119</codigo></sitio><sitio><nombre>Nkoléniong</nombre><codigo>2223993</codigo></sitio><sitio><nombre>Nkondongo</nombre><codigo>2223805</codigo></sitio><sitio><nombre>Abanga</nombre><codigo>2236127</codigo></sitio><sitio><nombre>Méboo</nombre><codigo>2227486</codigo></sitio></sitiosInteres></ciudad>

=== KiriBogach/arsoProject/xml-bd/508635.xml
<?xml version="1.0" ?>
<ciudad xmlns="http://www.example.org/ciudad"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/ciudad ../xml/ciudad.xsd">
	<nombre>Pochinki</nombre>
	<codigo>508635</codigo>
	<pais>RU</pais>
	<poblacion>11724</poblacion>
	<ubicacion>
		<latitud>54.69875</latitud>
		<longitud>44.86678</longitud>
	</ubicacion>
	<wikipedia>http://dbpedia.org/resource/Pochinki%2C_Pochinkovsky_District%2C_Nizhny_Novgorod_Oblast</wikipedia>
	<fechaActualizacion>2012-01-17</fechaActualizacion>
	<sitiosInteres>
		<sitio>
			<nombre>Pochinkovskiy Rayon</nombre>
			<codigo>508612</codigo>
		</sitio>
		<sitio>
			<nombre>Tagayevo</nombre>
			<codigo>484899</codigo>
		</sitio>
		<sitio>
			<nombre>Novospasskoye</nombre>
			<codigo>517891</codigo>
		</sitio>
		<sitio>
			<nombre>Shishadeyevo</nombre>
			<codigo>6846126</codigo>
		</sitio>
		<sitio>
			<nombre>Styrsha</nombre>
			<codigo>6846127</codigo>
		</sitio>
		<sitio>
			<nombre>Il'inskoye</nombre>
			<codigo>557121</codigo>
		</sitio>
		<sitio>
			<nombre>Baykovo</nombre>
			<codigo>578547</codigo>
		</sitio>
		<sitio>
			<nombre>Osinki</nombre>
			<codigo>6846164</codigo>
		</sitio>
		<sitio>
			<nombre>Pos�lok Pen�kozavoda</nombre>
			<codigo>6846165</codigo>
		</sitio>
	</sitiosInteres>
</ciudad>

=== KiriBogach/arsoProject/xml-bd/2520058.xml
<?xml version="1.0" ?><ciudad xmlns="http://www.example.org/ciudad" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/ciudad ../xml/ciudad.xsd"><nombre>Cartagena</nombre><codigo>2520058</codigo><pais>ES</pais><poblacion>211996</poblacion><ubicacion><latitud>37.60512</latitud><longitud>-0.98623</longitud></ubicacion><bdpedia></bdpedia><wikipedia></wikipedia><fechaActualizacion>2012-03-04</fechaActualizacion><infoMeteorologica><tiempoObservacion>2019-02-24T04:30:00</tiempoObservacion><nombreEstacion>International airport of the Region of Murcia</nombreEstacion><temperatura>15.0</temperatura><nubes>clouds and visibility OK</nubes></infoMeteorologica><sitiosInteres><sitio><nombre>Parque Maestranza de Artilleria</nombre><codigo>10860321</codigo></sitio><sitio><nombre>Museo Histórico Militar de Cartagena</nombre><codigo>10280776</codigo></sitio><sitio><nombre>HUSA CARTAGONOVA Hotel &amp; Spa</nombre><codigo>6482678</codigo></sitio><sitio><nombre>Sercotel Alfonso XIII</nombre><codigo>6483755</codigo></sitio><sitio><nombre>Plaza San Francisco</nombre><codigo>10400375</codigo></sitio><sitio><nombre>Barrio del Foro Romano</nombre><codigo>10280774</codigo></sitio><sitio><nombre>Parque Arqueológico Cerro del Molinete</nombre><codigo>10280775</codigo></sitio><sitio><nombre>Sercotel Alfonso Xiii Ex-Best Western</nombre><codigo>10170453</codigo></sitio><sitio><nombre>SERCOTEL Carlos III</nombre><codigo>6505996</codigo></sitio></sitiosInteres></ciudad>
